### ISSUE TITLE
Intermittent errors with Gatsby Cloud builds 

### ISSUE THREAD

**Issue by Samic8** [cometkim/gatsby-plugin-typegen#109]
I'm getting this error occasionally with Gatsby Cloud builds. Triggering a new build usually results in another build that is successful without errors.

```
[typegen] An error on codegen GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbySanityImageFixed". GraphQLDocumentError: Unknown fragment "GatsbySanityImageFixed". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFixed". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbySanityImageFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbySanityImageFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbySanityImageFluid". GraphQLDocumentError: Unknown fragment "GatsbyImageSharpFluid". GraphQLDocumentError: Unknown fragment "GatsbySanityImageFluid".
```

**Comment by pascaloliv** [comment]
I'm facing the same issue on `GatsbyImageSharp` fragments  in my CI at the moment.
It randomly break my build (I'm using [Buddy](http://buddy.works))

FYI - I'm using `gatsby-plugin-typegen@2.2.1`

**Comment by daniel-trevino** [comment]
I've experienced the same error as you. In my case, I could only see this error after having a `gatsby clean` and trying to do `gatsby build` (without running `gatsby dev` beforehand)

Try to change the order on how you load the plugin in `gatsby-config`. In my case, moving it at the end of the array solved the issue.

Good luck 👍

**Comment by Samic8** [comment]
Hi @danielivert. I changed the order and still getting the error. Are you using Gatsby cloud?

**Comment by cometkim** [comment]
I believe it should be related to #113, affected by upstream behavior change.

But there is no time for maintenance these days 😢  will try my best this weekend

**Comment by Samic8** [comment]
Hi, @cometkim I'm happy to help with a PR to resolve this issue. But I may need some guidance. Let me know if my time would be helpful and if it's worth your time to explain the solution. Thanks!

**Comment by cometkim** [comment]
Hi @Samic8,

I was off here for months but now started over. You can watch the progress at #138. I'm going to change the behavior, so I don't recommend code contribution for now. But I will request you to test when the pre-release is ready.

**Comment by Samic8** [comment]
Hey @cometkim any update on this? I'm more than happy to help out fixing it if needed. Thanks!

**Comment by cometkim** [comment]
In v3, gatsby-plugin-typegen will not run on Gatsby Cloud env anymore.
