### ISSUE TITLE
Avoid usage of Maybe

### ISSUE THREAD

**Issue by akzhy** [cometkim/gatsby-plugin-typegen#134]
Hi,
Is it possible to avoid using `Maybe<T>` in the generated ts file? Currently whenever I am accessing a property I will have to ensure all the parent nodes are not undefined or it will throw error.

**Comment by cometkim** [comment]
Sorry @akzhy. I had missed the notification. I think this is a question about explicit vs implicit schema. I'll add a FAQ or document to explain this.

**Comment by akzhy** [comment]
Hey @cometkim no problem, I fixed the issue by using Gatsby's schema customisation. I just had to specify which fields were non nullable.
