### ISSUE TITLE
Github Sponsors / Open collective

### ISSUE THREAD

**Issue by Samic8** [cometkim/gatsby-plugin-typegen#156]
Hi @cometkim,

If you set up GitHub sponsors or open collective for this project. I would like to set up a monthly donation on behalf of Easy Agile.

Thanks!

**Comment by cometkim** [comment]
Hey @Samic8, Thanks for your amazing suggestion!

Actually, I had no idea about getting GitHub Sponsors or Open Collective, but it will definitely be a good option for me and future contributors.

I want this project to be merged into GatsbyJS somehow in some way. But I also wanna have enough time for good DX and stabilization.

Until then, I decided to receive financial contributions via Open Collective. It can lead to bug bounties for documentation or engineering work.

**Comment by cometkim** [comment]
Added docs for Open Collective from #163 

please open issue anytime If you have any other questions about this project :)
