### ISSUE TITLE
Specify supported node.js versions

### ISSUE THREAD

**Issue by simnalamburt** [cometkim/gatsby-plugin-typegen#165]
Type generation does not work as expected on Node.js v12. Should I consider this as a bug or an out-of-support usage?

I'll post reproduction steps later.

**Comment by cometkim** [comment]
What does that mean of "does not work as expected"? It should work well on node versions supported by gatsbyjs and graphql-code-generator. I tested it on v12.22.1 and code generation works fine.

What are the gatsby version and the codegen version?

**Comment by cometkim** [comment]
It has dropped support for Node.js v12.
