### ISSUE TITLE
Update @graphql-tools deps

### ISSUE THREAD

**Issue by nagiek** [cometkim/gatsby-plugin-typegen#169]
Hi,

Thank you for this project, it’s very helpful.

I wanted to ask if we could update the @graphql-tools deps of this project. There are a few bug fixes which this project would benefit from. Specifically, pull request [#3081](/ardatan/graphql-tools/pull/3081), which fixes a `checkValidationErrors` bug in @graphql-tools/utils.

This would be a major upgrade to v8 of the package. Apparently this is a breaking change, but hopefully not that hard to implement.

Thank you!

**Comment by cometkim** [comment]
Now all dependencies are up-to-date in v3.
