### ISSUE TITLE
How to run as part of pre script?

### ISSUE THREAD

**Issue by stretch0** [cometkim/gatsby-plugin-typegen#173]
Is it possible to run this plugin as part of a pre script?

Types get generated when developing which is fine but would good to then gitignore them and have them generated when a build happens. 

This mans when the next developer pulls down the code changes, the app wont run because it can't start with missing types / interfaces. 

Running a codegen in a pre start script of some description would solve this. Is this possible?

**Comment by cometkim** [comment]
No. Because this plugin is deeply dependent on the GatsbyJS process, it cannot currently be run independently.

Since v3, It may provide a feature flag to kill the gatsby process immediately after emmitting files.

**Comment by stretch0** [comment]
Does that mean `__generated__/gatsby-types.ts` can't be gitignored?

**Comment by cometkim** [comment]
... If you want type-check first. I guess so.

**Comment by stretch0** [comment]
Actually, nvm. Just realised it's because we were running our `tsc` command before the app had started

```
"start": "tsc && gatsby develop",
```

Have moved `tsc` to poststart script now

```
"start": "gatsby develop",
"poststart": "tsc",
```

**Comment by cometkim** [comment]
Hmm well, Just sayin fyi

Since types in GatsbyJS are inferred after the query compiler is executed, there is no way to check it completely before that process done at least once.
