### ISSUE TITLE
graphql-tag-plunk is not found

### ISSUE THREAD

**Issue by cometkim** [cometkim/gatsby-plugin-typegen#2]

**Comment by Kerumen** [comment]
Fixed by `graphql-toolkit` in [v0.6.8](https://github.com/ardatan/graphql-toolkit/issues/308#issuecomment-550592273)!

**Comment by Kerumen** [comment]
Do you plan to release a new version with the upgraded packages? I would love to use this plugin but I'm stuck on this error..

They were some breaking changes in [v0.6.0](https://github.com/ardatan/graphql-toolkit/releases/tag/v0.6.0) which make the upgrade non-trivial.

**Comment by cometkim** [comment]
Resolved via #22
