### ISSUE TITLE
Feature: Suport d.ts output (global declarations)

### ISSUE THREAD

**Issue by cometkim** [cometkim/gatsby-plugin-typegen#24]

**Comment by xndyz** [comment]
Not having to manually import the types would be **amazing**. Would make this plugin a no brainer for every Gatsby dev.

**Comment by cometkim** [comment]
It seems to not able to be done with only codegen configurations. (Or I couldn't figure out how)

The simplest way I found is:

1. Use the `noExport: true` option.
2. Find all type|interface definitions and prepand the `declare` keyword.
3. Make file extension to '.d.ts' instead of '.ts'

**Comment by cometkim** [comment]
Obviously, Flow can also use a global declaration, so this new option should be treated as a mixed config, not a new language.

The codegen's Flow plugins don't support `noExport` option yet. I can preferentially release the TypeScript support during waiting for it or contributing directly.

**Comment by cometkim** [comment]
If the declaration scope is global, some declaration like `File` is conflicted.

In order to use a declaration, it must specify namespace scope or using the global namespace with a prefix to avoid conflicts.

flow has no namespace syntax, so it must use prefixes.

**Comment by cometkim** [comment]
Hey @fandy, I just published v2.0.0 that uses global declaration by default. Please try to migrate, and feedback will be appreciated.

**Comment by xndyz** [comment]
Generation like a charm! Would be great if it could automatically sync the types to page queries, but I understand that'd be harder to implement.

**Comment by xndyz** [comment]
Additional feedback: would be super useful to be able to import the field types, meaning not just the query, but the types for the fields in those queries.
