### ISSUE TITLE
Inline Fragments aren't exported

### ISSUE THREAD

**Issue by johnrom** [cometkim/gatsby-plugin-typegen#45]
I was led to this plugin due to an issue I had [over at `gatsby-plugin-graphql-codegen`](https://github.com/d4rekanguok/gatsby-typescript/issues/54). The author recommended I try this plugin to see if it solved it, and it didn't, so I figured I'd open an issue here as well.

There's more context on the other issue, but generally the inline fragments that are generated on subtypes of an interface aren't exported, leading to a need to duplicate those types.

```ts
//
// the inline fragments below generate useful types that aren't exported
//
export const WidgetFragment = graphql`
  fragment WidgetFragment on Widget {
    widgetId
    widgetType
    ... on ImageListWidget {
      images {
        ...ImageFragment
      }
    }
    ... on ImageWidget {
      image {
        ...ImageFragment
      }
    }
  }
`;

//
// these types aren't exported, so cannot be used as WidgetProps
//
type WidgetFragment_ImageSliderWidget_Fragment = (
  Pick<ImageSliderWidget, 'widgetId' | 'widgetType'>
  & { images: Array<Maybe<ImageFragmentFragment>> }
);

type WidgetFragment_ImageWidget_Fragment = (
  Pick<ImageWidget, 'widgetId' | 'widgetType'>
  & { image: Maybe<ImageFragmentFragment> }
);

//
// only this type is exported
//
export type WidgetFragmentFragment = WidgetFragment_ImageSliderWidget_Fragment | WidgetFragment_ImageWidget_Fragment;
```

**Comment by johnrom** [comment]
Looks like the missing config setting is below. I wonder if this can be configured outside of your plugin in a config file? I'm not sure if codegen.yml can be inherited by CLI configuration. Let me know if there's some way to override the configuration or if you're willing to export these types in the default configuration, in which case I can open a PR.

I confirmed making this change in `node_modules/gatsby-plugin-typegen/workers/codegen.js` does what I need.

[`@graphql-codegen/typescript-operations`: `config.exportFragmentSpreadSubTypes`](https://graphql-code-generator.com/docs/plugins/typescript-operations#exportfragmentspreadsubtypes-boolean-default-value-false)

**Comment by cometkim** [comment]
>  I wonder if this can be configured outside of your plugin in a config file?

@johnrom Unfortunately, you can't. (see the [disclaimer section]( https://github.com/cometkim/gatsby-plugin-typegen#disclaimer)) I will add that option right next release. I can imagine some use cases where the subtype export can be useful, but can you explain your use case in more detail?

And I wonder if the schema used in your example was created with Schema customization. If so, is there anything that this plugin can help with?

**Comment by johnrom** [comment]
Anywhere you might receive an array of different objects from a query that map to different components, the types generated from the various fragments map 1-to-1 to the component props. Without these exports, one must duplicate those types unnecessarily. For example, the components that make up a dynamic CMS page, or results from a search returning different types of objects.

**Comment by cometkim** [comment]
Rather than putting dependency fragments on components and joining them in a query, you prefer to write a query first and then create subcomponents based on that (generated) type. Is this your use case? (It's only to understand use cases correctly.)

**Comment by johnrom** [comment]
Yes, in the example I gave in the initial descriptions, you can see the exact prop types for `<ImageWidget />` and `<ImageSliderWidget />` are created but not exposed. This is for spread subtype fragments. I could maybe go with a union type as a workaround if those fragments are exported (haven't tried), but it doesn't make that much sense since these types inherit from a common interface.
