### ISSUE TITLE
(non issue) just wanna say hi

### ISSUE THREAD

**Issue by d4rekanguok** [cometkim/gatsby-plugin-typegen#5]
Hey @cometkim, it looks like we both have the same idea for graphql codegen (we're also both based in SK, though I don't speak Korean)! I wrote mine a while ago as a part of a different gatsby typescript related plugin, but recently [extracted it here](https://github.com/d4rekanguok/gatsby-typescript/tree/master/packages/gatsby-plugin-graphql-codegen).

We should have a chat & compare notes sometimes! Happy Chuseok.

**Comment by cometkim** [comment]
Hey @d4rekanguok.

Yeah we both seem to be interested in TypeScript and Gatsby plugins. Feel free to email, metion/DM @KrComet on twitter anytime. Or meet in seoul and talk about Gatsby if you want :wink:
