### ISSUE TITLE
[Feature] type insertion controls

### ISSUE THREAD

**Issue by Js-Brecht** [cometkim/gatsby-plugin-typegen#60]
I can see how the "type insertion" feature can be pretty handy... however, I just wanted to ask if you would be willing to allow some control over it.

AFAICT, it will always do type insertion, so long as the file is a typescript (or flow) file.  90% of the time, I prefer adding my own types, and don't want plugins changing my code, except with my explicit permission.

Could there maybe be an option to turn type insertion on/off?

**Comment by Js-Brecht** [comment]
So, I just looked, and you already do.  I was just slow in looking.... sorry!

**Comment by cometkim** [comment]
Haha, no worries.

yes, you can control that behavior by the `autoFix` option.
