### ISSUE TITLE
Errors out when you use fragments that are not locally on Gatbsy

### ISSUE THREAD

**Issue by xndyz** [cometkim/gatsby-plugin-typegen#7]
This plugin will break when you're using Apollo on the client and have any graphql that's not accessible by Gatsby. A possible fix for this is to exclude certain paths in the options.

**Comment by sdobz** [comment]
@fandy Does this PR fix your issue?

**Comment by xndyz** [comment]
It should fix it, but I'm not sure how to test it out.

**Comment by six5536** [comment]
I am also using Apollo and have the same clash problem.
I think it would be cool to extend this plugin to generate the Apollo types too. Would not be too hard. I might be able to do it in the coming week or two, but can't promise it.

**Comment by cometkim** [comment]
Hey @fandy @relefant, the @sdobz's fix just have merged into master. see #11 

you can use 0.3.0-alpha.0; I'm planning a stable release in middle of this month with more enhancements.
