### ISSUE TITLE
Plugin documents not generated during `gatsby develop` but exist after `gatby build`

### ISSUE THREAD

**Issue by adonig** [cometkim/gatsby-plugin-typegen#98]
`gatsby-plugin-documents.graphql` is missing during `gatsby develop`. It gets generated when I run `gatsby build` though. Downgrading gatsby to 2.24.8 does not fix this issue. I cloned the current master of `gatby-plugin-typegen` and added some `reporter.verbose` to `gatby-node.js` to see what's going on. That way I found out the `trackedSource` is empty during develop, causing the control flow to skip the conditional in line 175. The other files (`gatsby-schema.graphql`, `gatsby-introspection.json` and `gatsby-types.ts`) get generated though.

**Comment by cometkim** [comment]
I accidentally got a repro https://github.com/devsisters/gatsby-starter-typescript-workspace 😅 

will fix soon!

**Comment by cometkim** [comment]
@adonig you can keep track of this issue on #113
